version: "3.7"


services: 
  sim:
    container_name: simulation_sim
    build:
      context: ./Sim-master
      dockerfile: Dockerfile
    ports:
        - 4840:4841
        - 81:81
        - 5900:5900
        
  backend:
    container_name: back-end
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports: 
      - 8080:8080
    depends_on:
      - sim
