name: Integration test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 24
    steps:
      - name: ip install and check 
        run: ifconfig
      - name: Checkout
        uses: actions/checkout@v2
        with:
           ref: main
      - name: Build and run containers
        working-directory: ./
        run: docker-compose up -d && echo sleeping 90 seconds && sleep 90
      - name:  container inspection
        run: docker ps -a
      - name: Install Node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install test dependencies
        working-directory: ./integrationTest/testFiles/
        run: npm install newman 
      - name: Run test
        working-directory: ./integrationTest/testFiles/
        run: npm test || exit 1
