name: Integration test
on:
  push:
    branches:
      - IntegrationTestCI
  pull_request:
    branches:
      - IntegrationTestCI
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: ip check
        run: curl ifconfig.me
      - name: Checkout
        uses: actions/checkout@v2
        with:
           ref: IntegrationTestCI
      - name: Build and run
        working-directory: ./integrationTest/
        run: docker-compose up -d && echo sleeping 90 seconds && sleep 90
      - name:  Run inspection
        run: docker ps -a
      - name: Install Node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install test dependencies
        working-directory: ./integrationTest/testFiles/
        run: npm install newman 
      - name: Run test
        working-directory: ./integrationTest/testFiles/
        run: npm test
