name: testPipeline
on:
  push:
    branches:
      - IntegrationTestCI
  pull_request:
    branches:
      - IntegrationTestCI
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
           ref: IntegrationTestCI
      - name: Test
        working-directory: ./integrationTest/
        run: docker-compose up -d && echo sleeping 30 && sleep 120
      - name:  Testing
        run: docker ps -a
      - name: Use Node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: run and install test-directory
        working-directory: ./integrationTest/testFiles/
        run: npm install newman && curl http://localhost:8080/api/batches
      - name: test
        working-directory: ./integrationTest/testFiles/
        run: npm test
